### ISSUE TITLE
False output if sequence ends with NA in new line

### ISSUE THREAD

**Issue by mr-francois** [larssnip/microseq#1]
If sequence ends with NA in new line, the whole sequence becomes NA.
Example:
```
>header_1
AAAGGG
>header_2
TTGT
NA
>header_3
CTCTACT
```
leads to 
```
> fasta.file <- microseq::readFasta("~/temp.fasta")
> fasta.file
# A tibble: 3 x 2
  Header   Sequence
  <chr>    <chr>   
1 header_1 AAAGGG  
2 header_2 NA      
3 header_3 CTCTACT 
```

**Comment by larssnip** [comment]
Thanks for this. I believe I have corrected it. The fread function used in readFasta interprets a "NA" in the sequence as NA (Not Available). This has been turned off now.
