### ISSUE TITLE
 Leading / trailing quotation marks written in quality scores with writeFastq

### ISSUE THREAD

**Issue by AlexanderBartholomaeus** [larssnip/microseq#3]
Quotation marks are written in the quality scores

I don't know if this has to do with the bug fix of the old quotation mark issue?

**Comment by AlexanderBartholomaeus** [comment]
The problem seems to be the `fwrite` function used in `writeFastq` because quote is set to `"auto"` per default. If using the same function but with `quote=F` it works perfect. The row would be:

```
fwrite(tbl, file = out.file, compress = "auto", col.names = F, quote=F)
```

**Comment by larssnip** [comment]
Thanks for this. Yes, I did that change for writeFasta, some time ago, but seems to have forgotten to do the same for writeFastq. Now it should be updated.

**Comment by AlexanderBartholomaeus** [comment]
Perfect, thank you for the fast fix!

Best,
Alex
